### ISSUE TITLE
FileChooser crashes with 1.9.9-SNAPSHOT

### ISSUE THREAD

**Issue by WickedShell** [kotcrab/vis-editor#291]
I get a crash when attempting to open a `FileChooser` (although I suspect the error is fundamentally tied to the `Tooltip`'s), this appears to be a compatibility problem with 1.9.9-SNAPSHOT. Rolling back to a snapshot from several months ago it is bale to choose files correctly. I haven't done a full bisection search to find when the problem was induced, looking at the current code it's not jumping out to me as to why there is an issue.

```
15:44:30.015 ERROR [GDX] #object[java.lang.Thread 0x11e20997 Thread[GDX,5,main]] #error {
 :cause com.badlogic.gdx.scenes.scene2d.Actor.getListeners()Lcom/badlogic/gdx/utils/Array;
 :via
 [{:type com.badlogic.gdx.utils.GdxRuntimeException
   :message java.lang.NoSuchMethodError: com.badlogic.gdx.scenes.scene2d.Actor.getListeners()Lcom/badlogic/gdx/utils/Array;
   :at [com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application <init> Lwjgl3Application.java 117]}
  {:type java.lang.NoSuchMethodError
   :message com.badlogic.gdx.scenes.scene2d.Actor.getListeners()Lcom/badlogic/gdx/utils/Array;
   :at [com.kotcrab.vis.ui.widget.Tooltip attach Tooltip.java 145]}]
 :trace
 [[com.kotcrab.vis.ui.widget.Tooltip attach Tooltip.java 145]
  [com.kotcrab.vis.ui.widget.Tooltip init Tooltip.java 113]
  [com.kotcrab.vis.ui.widget.Tooltip <init> Tooltip.java 70]
  [com.kotcrab.vis.ui.widget.Tooltip <init> Tooltip.java 43]
  [com.kotcrab.vis.ui.widget.Tooltip$Builder build Tooltip.java 363]
  [com.kotcrab.vis.ui.widget.VisImageButton <init> VisImageButton.java 60]
  [com.kotcrab.vis.ui.widget.file.internal.FileHistoryManager <init> FileHistoryManager.java 53]
  [com.kotcrab.vis.ui.widget.file.FileChooser createToolbar FileChooser.java 292]
  [com.kotcrab.vis.ui.widget.file.FileChooser init FileChooser.java 232]
  [com.kotcrab.vis.ui.widget.file.FileChooser <init> FileChooser.java 180]
  [com.kotcrab.vis.ui.widget.file.FileChooser <init> FileChooser.java 163]
  [swiftgcs.gui_helpers$fn__13312 invokeStatic gui_helpers.clj 1131]
  [swiftgcs.gui_helpers$fn__13312 invoke gui_helpers.clj 1131]
  [clojure.lang.Delay deref Delay.java 42]
  [clojure.core$deref invokeStatic core.clj 2312]
  [swiftgcs.gui_helpers$choose_file$fn__13314 invoke gui_helpers.clj 1140]
  [clojure.lang.AFn run AFn.java 22]
  [com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application loop Lwjgl3Application.java 153]
  [com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application <init> Lwjgl3Application.java 111]
  [swiftgcs.gui$fn__26828 invokeStatic gui.clj 572]
  [swiftgcs.gui$fn__26828 invoke gui.clj 572]
  [clojure.lang.Delay deref Delay.java 42]
  [clojure.core$deref invokeStatic core.clj 2312]
  [swiftgcs.core$_main$fn__27164 invoke core.clj 97]
  [clojure.lang.AFn run AFn.java 22]
  [java.lang.Thread run Thread.java 748]]}

```

I was using the following artifacts:
```
                 [com.badlogicgames.gdx/gdx "1.9.9-SNAPSHOT"]
                 [com.badlogicgames.gdx/gdx-backend-lwjgl3 "1.9.9-SNAPSHOT"]
                 [com.badlogicgames.gdx/gdx-controllers "1.9.9-SNAPSHOT"]
                 [com.badlogicgames.gdx/gdx-controllers-lwjgl3 "1.9.9-SNAPSHOT"]
                 [com.badlogicgames.gdx/gdx-controllers-platform "1.9.9-SNAPSHOT" :classifier "natives-desktop"]
                 [com.badlogicgames.gdx/gdx-platform "1.9.9-SNAPSHOT" :classifier "natives-desktop"]
                 [com.kotcrab.vis/vis-ui "1.4.0"]
                 [com.kotcrab.vis/vis-ui-contrib "1.3.0"]   
```

**Comment by kotcrab** [comment]
https://github.com/kotcrab/vis-editor/wiki/VisUI#libgdx-compatibility

Mismatched versions can work but this depends on what was changed in libgdx. Not this time tough, `getListeners` signature was changed from
```java
public Array<EventListener> getListeners ()
```
to
```java
public DelayedRemovalArray<EventListener> getListeners ()
```
Which from bytecode perspective is a different method. 
VisUI has to be build with 1.9.9-SNAPSHOT to fix this.

**Comment by kotcrab** [comment]
Yeah, I'll try to do it this weekend.

**Comment by kotcrab** [comment]
To avoid breaking existing builds I've released `1.4.1` as-is, next version is `1.4.2-SNAPSHOT` which is build with `1.9.9-SNAPSHOT`. Not a huge fan of building it against a snapshot but I guess it would be fine given lack of libgdx releases.

**Comment by EtK2000** [comment]
Thank you so much!

**Comment by WickedShell** [comment]
> Not a huge fan of building it against a snapshot but I guess it would be fine given lack of libgdx releases.

I'm not either, but I needed a specific feature which is in the LibGDX snapshots, and couldn't really afford to wait unfortunately. Anyways this resolved the issue, so thank you!

**Comment by MinuteMan721** [comment]
Hello everyone, I'm running into this problem "java.lang.NoSuchMethodError: com.badlogic.gdx.scenes.scene2d.Actor.getListeners()Lcom/badlogic/gdx/utils/Array;"

Can someone point me in the right direction of how to fix this...like where in Android Studio I should add --verbose:class when running the app?  Everywhere online says just add this code, that code, but where should it be added in the system?   I can't seem to find it.  Thanks

**Comment by kotcrab** [comment]
@MinuteMan721 you don't need `--verbose:class`, you need to fix your dependency versions. See this table and make sure your libgGDX and VisUI versions are matching https://github.com/kotcrab/vis-ui#libgdx-compatibility

**Comment by MinuteMan721** [comment]
Thanks
